### ISSUE TITLE
Win10: TypeError running user password set

### ISSUE THREAD

**Issue by Szandor72** [mshanemc/shane-sfdx-plugins#39]
sfdx shane:user:password:set -p sf1234dc -g User -l User -u myAlias

```
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:/Users/szand/AppData/Local/sfdx/node_modules/@salesforce/command/node_modules/@salesforce/core/lib/crypto.js:58:28)
    at Module._compile (C:/Users/szand/AppData/Local/sfdx/client/7.4.0-99233fd3af/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Function._load (C:/Users/szand/AppData/Local/sfdx/client/7.4.0-99233fd3af/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:89:24)
    at require (C:/Users/szand/AppData/Local/sfdx/client/7.4.0-99233fd3af/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:/Users/szand/AppData/Local/sfdx/node_modules/@salesforce/command/node_modules/@salesforce/core/lib/config/config.js:11:18)
```

Is there more info I can provide next to this exception message?

**Comment by mshanemc** [comment]
can you do all the version updates and try it?  

And maybe post the output of `sfdx version` and `sfdx plugins`

**Comment by Szandor72** [comment]
oh, I missed 7.5. but problem persists. 

sfdx -v 
`sfdx-cli/7.5.0-e6ca93eee8 win32-x64 node-v10.15.3`

```
@salesforce/analytics 0.6.0
generator 1.1.0
├─ @oclif/plugin-help 2.1.6
├─ @oclif/plugin-warn-if-update-available 1.7.0
└─ @oclif/plugin-not-found 1.2.2

shane-sfdx-plugins 3.14.1
```

current error
```
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:/Users/szand/AppData/Local/sfdx/node_modules/@salesforce/command/node_modules/@salesforce/core/lib/crypto.js:58:28)
    at Module._compile (C:/Users/szand/AppData/Local/sfdx/client/7.5.0-e6ca93eee8/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Function._load (C:/Users/szand/AppData/Local/sfdx/client/7.5.0-e6ca93eee8/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:89:24)
    at require (C:/Users/szand/AppData/Local/sfdx/client/7.5.0-e6ca93eee8/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:/Users/szand/AppData/Local/sfdx/node_modules/@salesforce/command/node_modules/@salesforce/core/lib/config/config.js:11:18)
```

**Comment by rbergman** [comment]
It looks like it's coming from this line of `@salesforce/core/lib/crypto.js`:

```
class Crypto extends kit_1.AsyncOptionalCreatable {
```

Usually this error means that there's a circular import between modules (e.g. crypto depends on kit which depends on crypto, though in this case that is not true) and Node's module system returns an empty module object when the first module in the cycle is not yet fully loaded, leading to an undefined reference of the target class being extended.

Since kit does not depend on core, though, there must be another explanation.  One possibility is that the lazy loader is returning an empty object when it shouldn't (which may mean that its module type cache is stale, though there are protections to try to prevent that).  You can try running the command again with the environment variable `SFDX_LAZY_LOAD_MODULES=false` set/exported.

If that helps, then the next step could be to try manually deleting the lazy loader's module cache, which can be found at `%LocalAppData%\sfdx\modules-types.json` and trying again.

If that still doesn't help, then you may somehow have gotten your node modules in a corrupted state.  You can try doing a full reinstall of the CLI using an [installer](https://developer.salesforce.com/media/salesforce-cli/sfdx-windows-amd64.exe) rather than the updater.  This will fully reset the CLI sources and caches to ensure a clean installation.

If that still doesn't help, perhaps the plugin is influencing something.

**Comment by mshanemc** [comment]
Thanks @rbergman.  I haven't been able to get the issue.  @Szandor72 can you try these new ideas and see if anything helps (and maybe share so we can figure out if it's something we can fix)

**Comment by Szandor72** [comment]
Will do, might take a little time.

**Comment by Szandor72** [comment]
Setting $env:SFDX_LAZY_LOAD_MODULES='false'
did not change behaviour. To my knowledge, Environment Vars are only supported on Mac/Linux. Cf. 
https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_cli_env_variables.htm

Deleting `module-types.json` was unsuccessful, too.

The very same error also appears doing other shane commands, e.g. `shane:mdapi:describe -h`

Re-Installing the CLI via given link did not change behaviour, either. 

Are there

**Comment by rbergman** [comment]
Ok, well that rules out my concerns about the CLI being to blame, but it means this is still a mystery.  The CLI does support environment variables on Windows, FWIW.

**Comment by Szandor72** [comment]
Quick update: new machine, clean install, no issues. 

I will close this for now.
